### Login
POST http://localhost:9420/login
Content-Type: application/json

{
    "username": "test@pfgbulgaria.com",
    "password": "test@pfgbulgaria.com"
}

### GetNews

GET http://localhost:9420/news
Content-Type: application/json
Authorization: Bearer 5cgqinbofaahdavfcwuxme2t8i564lds3h0mv4sr6ts6h9hqjkldtqdmms0jlyeo